# Generated by Django 4.0.5 on 2022-06-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_employee_manager_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.TimeField(blank=True, verbose_name='CheckIn Time')),
                ('checkout', models.TimeField(blank=True, verbose_name='CheckOut Time')),
                ('totalhours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('attendancefor', models.DateTimeField(auto_now=True)),
                ('remarks', models.CharField(max_length=120, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'ordering': ['-created'],
            },
        ),
    ]
