# Generated by Django 4.0.4 on 2022-05-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=64)),
                ('emp_id', models.CharField(max_length=64)),
                ('emp_email', models.EmailField(max_length=128)),
                ('manager_name', models.CharField(max_length=64, null=True)),
                ('manager_id', models.CharField(max_length=64, null=True)),
                ('manager_email', models.EmailField(max_length=128, null=True)),
                ('current_role', models.CharField(max_length=64)),
                ('past_roles', models.CharField(max_length=512)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('Expiration_date', models.DateTimeField(blank=True, null=True)),
                ('desk_location', models.CharField(max_length=64)),
            ],
        ),
    ]
